language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t danimerida2000/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true danimerida2000/docker-react npm run test -- --coverage
